adminapp/urls.py
from django.urls import path
from adminapp.views import users, categories, products

app_name = 'adminapp'
urlpatterns = [
    path('users/read/', users.UserListView.as_view(), name='users'),
    path('users/delete/<int:pk>', users.UserDeleteView.as_view(), name='user_delete'),

    path('categories/create', categories.ProductCategoryCreateView.as_view(), name='category_create'),
    path('categories/read/', categories.ProductCategoryListView.as_view(), name='categories'),
    path('categories/update/<int:pk>', categories.ProductCategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>', categories.ProductCategoryDeleteView.as_view(), name='category_delete'),

    path('products/create/category/<int:pk>', products.product_create, name='product_create'),
    path('products/read/category/<int:pk>', products.products, name='products'),
    path('products/read/<int:pk>', products.ProductDetailView.as_view(), name='product_read'),
    path('products/update/<int:pk>', products.product_update, name='product_update'),
    path('products/delete/<int:pk>', products.ProductDeleteView.as_view(), name='product_delete'),
]

authapp/urls.py
from django.urls import path, re_path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.verify, name='verify'),
]

geekshop/urls.py
import debug_toolbar

import mainapp.views as mainapp
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from geekshop import settings

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('', include('social_django.urls', namespace='social')),
    path('product/', mainapp.product, name='product'),
    path('catalog/', include('mainapp.urls', namespace='catalog')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('contacts/', mainapp.contacts, name='contacts'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('admin/', include('adminapp.urls', namespace='admin')),
    path('order/', include('ordersapp.urls', namespace='order')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/forms.py
from django import forms

from authapp.models import ShopUser
from mainapp.models import Product, ProductCategory


class ShopUserAdminEditForm(forms.ModelForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'email', 'age', 'avatar')

    def __init__(self, *args, **kwargs):
        super(ShopUserAdminEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductCategoryEditForm(forms.ModelForm):
    discount = forms.IntegerField(label='скидка', required=False, min_value=0, max_value=90, initial=0)

    class Meta:
        model = ProductCategory
        # fields = '__all__'
        exclude = ()


    def __init__(self, *args, **kwargs):
        super(ProductCategoryEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class ProductAdminEditForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ProductAdminEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

adminapp/views.py
from django.contrib.auth.decorators import user_passes_test
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.shortcuts import get_object_or_404, render
from django.utils.decorators import method_decorator
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from mainapp.models import Product, ProductCategory
from authapp.models import ShopUser
from .forms import ShopUserEditForm, ShopUserCreateForm
from .forms import ProductCategoryEditForm, ProductCategoryCreateForm
from .forms import ProductCreateForm, ProductEditForm


@user_passes_test(lambda u: u.is_superuser)
def index(request):
    return HttpResponseRedirect(reverse('adminapp:categories'))


class UsersListView(ListView):
    model = ShopUser
    template_name = 'adminapp/users.html'
    context_object_name = 'objects'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'админка/пользователи'
        return context


class UserCreateView(CreateView):
    model = ShopUser
    template_name = 'adminapp/user_create.html'
    form_class = ShopUserCreateForm
    success_url = reverse_lazy('adminapp:users')

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'админка/пользователи/создание'
        return context


class UserUpdateView(UpdateView):
    model = ShopUser
    template_name = 'adminapp/user_edit.html'
    form_class = ShopUserEditForm

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'админка/пользователи/редактирование'
        return context

    def form_valid(self, form):
        user = form.save(commit=False)
        user.save()
        return HttpResponseRedirect(reverse_lazy('adminapp:user_update', kwargs={'pk': user.pk}))


class UserDeleteView(DeleteView):
    model = ShopUser
    template_name = 'adminapp/user_delete.html'
    context_object_name = 'user_to_delete'
    success_url = reverse_lazy('adminapp:users')

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'админка/пользователи/удаление'
        return context


class CategoriesListView(ListView):
    model = ProductCategory
    template_name = 'adminapp/categories.html'
    context_object_name = 'objects'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'админка/категории'
        return context


class CategoryCreateView(CreateView):
    model = ProductCategory
    template_name = 'adminapp/category_create.html'
    form_class = ProductCategoryCreateForm

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'админка/категории/создание'
        return context


class CategoryUpdateView(UpdateView):
    model = ProductCategory
    template_name = 'adminapp/category_edit.html'
    form_class = ProductCategoryEditForm

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'админка/категории/редактирование'
        return context

    def form_valid(self, form):
        category = form.save(commit=False)
        category.save()
        return HttpResponseRedirect(reverse_lazy('adminapp:category_update', kwargs={'pk': category.pk}))


class CategoryDeleteView(DeleteView):
    model = ProductCategory
    template_name = 'adminapp/category_delete.html'
    context_object_name = 'category_to_delete'
    success_url = reverse_lazy('adminapp:categories')

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'админка/категории/удаление'
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()

        return HttpResponseRedirect(self.get_success_url())


class ProductsListView(ListView):
    template_name = 'adminapp/products.html'
    context_object_name = 'objects'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get(self, request, *args, **kwargs):
        self.cat_pk = self.kwargs['pk']
        self.queryset = Product.objects.filter(category__pk=self.cat_pk).order_by('name')
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'админка/продукт'
        context['category'] = ProductCategory.objects.get(pk=self.cat_pk)
        context['objects'] = Product.objects.filter(category__pk=self.cat_pk).order_by('name')
        return context


class ProductCreateView(CreateView):
    model = Product
    template_name = 'adminapp/product_create.html'
    form_class = ProductCreateForm

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'админка/продукты/создание'
        context['category_pk'] = self.cat_pk
        return context

    def get(self, request, *args, **kwargs):
        self.cat_pk = self.kwargs['pk']
        return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        new_product = form.save(commit=False)
        new_product.category_id = self.kwargs['pk']
        new_product.save()

        return HttpResponseRedirect(reverse_lazy('adminapp:products', kwargs={'pk': self.kwargs['pk']}))


def product_read(request, pk):
    pass


class ProductUpdateView(UpdateView):
    model = Product
    template_name = 'adminapp/product_edit.html'
    form_class = ProductEditForm

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'админка/продукты/редактирование'
        context['category_id'] = self.cat_pk
        return context

    def get(self, request, *args, **kwargs):
        product = Product.objects.get(pk=kwargs['pk'])
        self.cat_pk = product.category_id
        return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        product = form.save(commit=False)
        product.save()
        return HttpResponseRedirect(reverse_lazy('adminapp:product_update', kwargs={'pk': product.pk}))


class ProductDeleteView(DeleteView):
    model = Product
    template_name = 'adminapp/product_delete.html'
    context_object_name = 'product_to_delete'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'админка/продукты/удаление'
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()

        return HttpResponseRedirect(reverse_lazy('adminapp:products', kwargs={'pk': self.object.category_id}))

adminapp/views/categories.py
from django.contrib.auth.decorators import user_passes_test
from django.db import connection
from django.db.models import F
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView

from adminapp.forms import ProductCategoryEditForm
from adminapp.views.products import db_profile_by_type
from mainapp.models import ProductCategory


class ProductCategoryListView(ListView):
    model = ProductCategory
    template_name = 'adminapp/categories.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'admin / categories'
        return context


class ProductCategoryCreateView(CreateView):
    model = ProductCategory
    template_name = 'adminapp/category_update.html'
    success_url = reverse_lazy('admin:categories')
    form_class = ProductCategoryEditForm

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'categories / create'
        return context


class ProductCategoryUpdateView(UpdateView):
    model = ProductCategory
    template_name = 'adminapp/category_update.html'
    success_url = reverse_lazy('admin:categories')
    form_class = ProductCategoryEditForm

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'categories / change'
        return context

    def form_valid(self, form):
        if 'discount' in form.cleaned_data:
            discount = form.cleaned_data['discount']
            if discount:
                self.object.product_set.update(price=F('price') * (1 - discount / 100))
                db_profile_by_type(self.__class__, 'UPDATE', connection.queries)

        return super().form_valid(form)


class ProductCategoryDeleteView(DeleteView):
    model = ProductCategory
    template_name = 'adminapp/category_delete.html'
    success_url = reverse_lazy('admin:categories')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.is_active:
            self.object.is_active = False
        else:
            self.object.is_active = True
        self.object.save()
        self.object.save()
        return HttpResponseRedirect(self.success_url)

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'categories / delete'
        return context

adminapp/views/users.py
from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic.edit import DeleteView
from django.views.generic.list import ListView

from authapp.models import ShopUser


class UserListView(ListView):
    model = ShopUser
    template_name = 'adminapp/users.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super(UserListView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'admin / users'
        return context

class UserDeleteView(DeleteView):
    model = ShopUser
    template_name = 'adminapp/user_delete.html'
    success_url = reverse_lazy('admin:users')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        print(request.resolver_match.url_name)
        if self.object.is_active:
            self.object.is_active = False
        else:
            self.object.is_active = True
        self.object.save()

        return HttpResponseRedirect(self.get_success_url())

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'admin / users'
        return context

adminapp/templates/adminapp/categories.html
{% extends 'mainapp/page-layout.html' %}
{% load static %}

{% block header %}
    {% include 'adminapp/includes/inc_menu.html' %}
{% endblock %}

{% block content %}
    <div class="wrapper">
        <div class="container">
            <div class="categories_list">
                <button class="new_category">
                    <a href={% url 'admin:category_create' %}>New category</a>
                </button>
                <hr>
                {% for object in object_list %}
                    <div class="category_record {% if not object.is_active %}not_active{% endif %}">
                        <div class="category_name">
                            {{ object.name|title }}
                        </div>
                        <div class="category_actions">
                            <button>
                                <a href={% url 'admin:products' object.pk %}>Products</a>
                            </button>
                            <button>
                                <a href={% url 'admin:category_update' object.pk %}>Edit</a>
                            </button>
                            <button>
                                {% if object.is_active %}
                                    <a href={% url 'admin:category_delete' object.pk %}>Delete</a>
                                {% else %}
                                    <a href={% url 'admin:category_delete' object.pk %}>Restore</a>
                                {% endif %}
                            </button>
                        </div>
                        <div class="category_desc">
                            {{ object.description }}
                        </div>
                    </div>
                    <hr>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

adminapp/templates/adminapp/category_create.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<main>
    <div class="row">
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="form-control" type="submit" value="сохранить">
        </form>
        <button class="btn btn-round form-control last">
            <a href="{% url 'adminapp:categories' %}" class="">
                к категориям
            </a>
        </button>
    </div>
</main>
{% endblock %}

adminapp/templates/adminapp/category_delete.html
{% extends 'mainapp/page-layout.html' %}
{% load static %}

{% block header %}
    {% include 'adminapp/includes/inc_menu.html' %}
{% endblock %}

{% block content %}
    <div class="wrapper">
        <div class="container">
            <div class="category_delete">
                Sure to {% if object.is_active %}delete{% else %}restore{% endif %} category <strong>
                {{ object.name|title }}</strong>?
                <form action="{% url 'admin:category_delete' object.pk %}" method="post">
                    {% csrf_token %}
                    <input class="btn btn-danger" type="submit"
                           value="{% if object.is_active %}Delete{% else %}Restore{% endif %}">
                </form>
                <button class="btn btn-success">
                    <a href="{% url 'admin:categories' %}">Cancel</a>
                </button>
            </div>
        </div>
    </div>
{% endblock %}

{% block footer %}
{% endblock %}

adminapp/templates/adminapp/category_edit.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<main>
    <div class="row">
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}

            <input class="form-control" type="submit" value="сохранить">
        </form>
        <button class="btn btn-round form-control last">
            <a href="{% url 'adminapp:categories' %}" class="">
                к категориям
            </a>
        </button>
    </div>
</main>
{% endblock %}

adminapp/templates/adminapp/category_update.html
{% extends 'mainapp/page-layout.html' %}
{% load static %}

{% block header %}
    {% include 'adminapp/includes/inc_menu.html' %}
{% endblock %}

{% block content %}
    <div class="wrapper">
        <div class="container">
            <div class="new_category_form">
                <form class="form-horizontal" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input class="form-control" type="submit" value="Save">
                </form>
                <button class="btn btn-round form-control last">
                    <a href="{% url 'admin:categories' %}">
                        Back
                    </a>
                </button>
            </div>
        </div>
    </div>
{% endblock %}

{% block footer %}
{% endblock %}

adminapp/templates/adminapp/product_create.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<main>
    <div class="row">
        <form class="form-horizontal" action="{% url 'adminapp:product_create' category_pk %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="form-control" type="submit" value="сохранить">
        </form>
        <button class="btn btn-round form-control last">
            <a href="{% url 'adminapp:products' category_pk %}" class="">
                к продуктам
            </a>
        </button>
    </div>
</main>
{% endblock %}

adminapp/templates/adminapp/product_delete.html
{% extends 'mainapp/page-layout.html' %}
{% load static %}
{% load avatar_tag %}

{% block header %}
    {% include 'adminapp/includes/inc_menu.html' %}
{% endblock %}

{% block content %}
    <div class="wrapper">
        <div class="container">
            <div class="product_delete">
                Sure to {% if object.is_active %}delete{% else %}restore{% endif %} product<strong>
                {{ object.name|title }}</strong>?
                <form action="{% url 'admin:product_delete' object.pk %}" method="post">
                    {% csrf_token %}
                    <input class="btn btn-danger" type="submit"
                           value="{% if object.is_active %}Delete{% else %} Restore{% endif %}">
                </form>
                <button class="btn btn-success">
                    <a href="{% url 'admin:products' object.category.pk %}">Cancel</a>
                </button>
            </div>
        </div>
    </div>
{% endblock %}

adminapp/templates/adminapp/product_edit.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<main>
    <div class="row">
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="form-control" type="submit" value="сохранить">
        </form>
        <button class="btn btn-round form-control last">
            <a href="{% url 'adminapp:products' category_id %}" class="">
                к продуктам
            </a>
        </button>
    </div>
</main>
{% endblock %}

adminapp/templates/adminapp/product_read.html
{% extends 'mainapp/page-layout.html' %}
{% load static %}
{% load avatar_tag %}

{% block header %}
    {% include 'adminapp/includes/inc_menu.html' %}
{% endblock %}

{% block content %}
    <div class="wrapper">
        <div class="container">
            <div class="product_read">
                <div class="product_name">
                    Продукт<strong>{{ object.category.name|title }} / {{ object.name|title }}</strong>
                </div>
                <img src="/media/{{ object.image|default:'products_images/default.png' }}" alt="{{ object.name }}">
                <div class="summary">
                    <b>Price</b>
                    <p>{{ object.price }} €</p>
                    <b>Quantity</b>
                    <p>{{ object.quantity }}</p>
                    <b>Active</b>
                    <p>{% if object.is_active %}Yes{% else %}No{% endif %}</p>
                    <p>
                        <button>
                            <a href={% url 'admin:product_update' object.pk %}>Change</a>
                        </button>
                    </p>
                    <p>
                        <button>
                            <a href={% url 'admin:product_delete' object.pk %}>Delete</a>
                        </button>
                    </p>
                    <p>
                        <button>
                            <a href={% url 'admin:products' object.category.pk %}>Back</a>
                        </button>
                    </p>
                </div>
                <div class="product_desc">
                    <b>Short description</b>
                    <p>
                        {{ object.short_desc }}
                    </p>
                    <br>
                    <br>
                    <b>Detais</b>
                    <p>
                        {{ object.description }}
                    </p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

adminapp/templates/adminapp/product_update.html
{% extends 'mainapp/page-layout.html' %}
{% load static %}


{% block header %}
    {% include 'adminapp/includes/inc_menu.html' %}
{% endblock %}

{% block content %}
    <div class="wrapper">
        <div class="container">
            <div class="new_category_form">
                <form class="form-horizontal" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ update_form.as_p }}
                    <input class="form-control" type="submit" value="Save">
                </form>
                <button class="btn btn-round form-control last">
                    <a href="{% url 'admin:products' category.pk %}">
                        Back
                    </a>
                </button>
            </div>
        </div>
    </div>
{% endblock %}

adminapp/templates/adminapp/products.html
{% extends 'mainapp/page-layout.html' %}
{% load static %}

{% block header %}
    {% include 'adminapp/includes/inc_menu.html' %}
{% endblock %}

{% block content %}
    <div class="wrapper">
        <div class="container">
            <div class="products_list">
                <button class="new_product"><a href={% url 'admin:product_create' category.pk %}>New product</a>
                </button>
                <hr>

                {% for object in objects %}
                    <div class="product_record {% if not object.is_active %}not_active{% endif %}">
                        <img src="/media/{{ object.image|default:'products_images/default.jpg' }}"
                             alt="{{ object.name }}">
                        <div class="product_name">
                            {{ object.name|title }}
                        </div>
                        <div class="product_actions">
                            <button>
                                <a href={% url 'admin:product_read' object.pk %}>Details</a>
                            </button>
                            <button>
                                <a href={% url 'admin:product_update' object.pk %}>Change</a>
                            </button>
                            <button>
                                {% if object.is_active %}
                                    <a href={% url 'admin:product_delete' object.pk %}>Delete</a>
                                {% else %}
                                    <a href={% url 'admin:product_delete' object.pk %}>Restore</a>
                                {% endif %}
                            </button>
                        </div>
                        <div class="summary">
                            <b>Price</b>
                            <p>{{ object.price }} €</p>
                            <b>Quantity</b>
                            <p>{{ object.quantity }}</p>
                        </div>
                        <div class="product_desc">
                            {{ object.short_desc|title }}
                        </div>
                    </div>
                    <hr>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

adminapp/templates/adminapp/user_delete.html
{% extends 'mainapp/page-layout.html' %}
{% load static %}
{% load avatar_tag %}

{% block header %}
    {% include 'adminapp/includes/inc_menu.html' %}
{% endblock %}

{% block content %}
    <div class="wrapper">
        <div class="container">
            <div class="user_delete">
                {% if object.is_active %}
                    Are you sure to block <b>{{ object.username }} {% if object.first_name %}
                    ({{ object.first_name|title }}
                    {% if object.last_name %}
                        {{ object.last_name|title }}
                    {% endif %})
                {% endif %}</b>?
                    <form action="{% url 'admin:user_delete' object.pk %}" method="post">
                        {% csrf_token %}
                        <input class="btn btn-danger" type="submit" value="Block">
                    </form>
                {% else %}
                    Are you sure to unblock <b> {{ object.username }} {% if object.first_name %}
                    ({{ object.first_name|title }}
                    {% if object.last_name %}
                        {{ object.last_name|title }}
                    {% endif %})
                {% endif %}</b>?
                    <form action="{% url 'admin:user_delete' object.pk %}" method="post">
                        {% csrf_token %}
                        <input class="btn btn-info" type="submit" value="Restore">
                    </form>
                {% endif %}
                <button class="btn btn-success">
                    <a href="{% url 'admin:users' %}">Cancel</a>
                </button>
            </div>
        </div>
    </div>
{% endblock %}