authapp/urls.py
from django.urls import path, re_path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.verify, name='verify'),
]

basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>/', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit'),
]

geekshop/urls.py
import debug_toolbar

import mainapp.views as mainapp
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from geekshop import settings

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('', include('social_django.urls', namespace='social')),
    path('product/', mainapp.product, name='product'),
    path('catalog/', include('mainapp.urls', namespace='catalog')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('contacts/', mainapp.contacts, name='contacts'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('admin/', include('adminapp.urls', namespace='admin')),
    path('order/', include('ordersapp.urls', namespace='order')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

mainapp/urls.py
import mainapp.views as mainapp
from django.urls import path

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.catalog, name='index'),
    path('category/<int:pk>/', mainapp.catalog, name='category'),
    path('category/<int:pk>/<int:page>/', mainapp.catalog, name='page'),
    path('product/<int:pk>/', mainapp.product, name='product'),
]

mainapp/models.py
from django.db import models

class ProductCategory(models.Model):
    name = models.CharField(verbose_name='Name', max_length=64, unique=True)
    description = models.TextField(verbose_name='Description', blank=True)
    is_active = models.BooleanField(db_index=True, default=True, verbose_name='Active')

    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='Name', max_length=128)
    image = models.ImageField(upload_to='product_images', blank=True)
    short_desc = models.CharField(verbose_name='Short description', max_length=60, blank=True)
    description = models.TextField(verbose_name='Description', blank=True)
    price = models.DecimalField(verbose_name='Price', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveSmallIntegerField(verbose_name='In stock', default=0)
    is_active = models.BooleanField(db_index=True, default=True, verbose_name='Active')

    def __str__(self):
        return f'{self.name} ({self.category.name})'

    @staticmethod
    def get_items():
        return Product.objects.filter(is_active=True).order_by('category', 'name')

adminapp/views/products.py
from django.db import connection
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.views.generic import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import user_passes_test
from django.urls import reverse, reverse_lazy
from django.shortcuts import get_object_or_404, HttpResponseRedirect, render

from adminapp.forms import ProductAdminEditForm
from authapp.models import ShopUser
from mainapp.models import Product, ProductCategory

def db_profile_by_type(prefix, type, queries):
   update_queries = list(filter(lambda x: type in x['sql'], queries))
   print(f'db_profile {type} for {prefix}:')
   [print(query['sql']) for query in update_queries]

@receiver(pre_save, sender=ProductCategory)
def product_is_active_update_productcategory_save(sender, instance, **kwargs):
   if instance.pk:
       if instance.is_active:
           instance.product_set.update(is_active=True)
       else:
           instance.product_set.update(is_active=False)

       db_profile_by_type(sender, 'UPDATE', connection.queries)

@user_passes_test(lambda u: u.is_superuser)
def products(request, pk):
    title = 'admin / products'
    category_item = get_object_or_404(ProductCategory, pk=pk)
    products_list = Product.objects.filter(category=category_item)
    content = {
        'title': title,
        'category': category_item,
        'objects': products_list
    }

    return render(request, 'adminapp/products.html', content)


@user_passes_test(lambda u: u.is_superuser)
def product_create(request, pk):
    title = 'product / create'
    category = get_object_or_404(ProductCategory, pk=pk)

    if request.method == 'POST':
        product_form = ProductAdminEditForm(request.POST, request.FILES)
        if product_form.is_valid():
            product_form.save()
            return HttpResponseRedirect(reverse('admin:products', args=[pk]))
    else:
        product_form = ProductAdminEditForm(initial={'category': category})

    content = {'title': title, 'update_form': product_form, 'category': category}

    return render(request, 'adminapp/product_update.html', content)


@user_passes_test(lambda u: u.is_superuser)
def product_update(request, pk):
    title = 'product / change'

    edit_product = get_object_or_404(Product, pk=pk)

    if request.method == 'POST':
        edit_form = ProductAdminEditForm(request.POST, request.FILES, instance=edit_product)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('admin:product_update', args=[edit_product.pk]))
    else:
        edit_form = ProductAdminEditForm(instance=edit_product)

    content = {'title': title, 'update_form': edit_form, 'category': edit_product.category}

    return render(request, 'adminapp/product_update.html', content)


class ProductDeleteView(DeleteView):
    model = Product
    template_name = 'adminapp/product_delete.html'

    def get_success_url(self):
        return reverse('admin:products', args=[self.get_object().category.pk])

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.is_active:
            self.object.is_active = False
        else:
            self.object.is_active = True
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'product / delete'
        return context


class ProductDetailView(DetailView):
    model = Product
    template_name = 'adminapp/product_read.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'product / details'
        return context

mainapp/views.py
import json
import os
import random

from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import get_object_or_404, render

from .models import Product, ProductCategory

JSON_PATH = 'mainapp/json'


def load_from_json(file_name):
    with open(os.path.join(JSON_PATH, file_name + '.json'), 'r') as infile:
        return json.load(infile)


def get_hot_product():
    products = Product.objects.filter(is_active=True, category__is_active=True, quantity__gte=1)
    return random.sample(list(products), 1)[0]


def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category, quantity__gte=1).exclude(pk=hot_product.pk)[
                    :3]

    return same_products


def main(request):
    products = Product.objects.filter(category__is_active=True, quantity__gte=1)[:3]
    context = {
        'copyright': 'Golubeva Lyubov - GB',
        'products': products,
        # 'new_products': Product.objects.all()[3:7],
    }
    # print(products.query)
    return render(request, 'mainapp/index.html', context)


def catalog(request, pk=None, page=1):
    links_menu = ProductCategory.objects.filter(is_active=True)

    if pk:
        if pk == '0':
            category = {
                'pk': 0,
                'name': 'all'
            }
            products = Product.objects.filter(is_active=True, category__is_active=True, quantity__gte=1).order_by(
                'price')
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True,
                                              quantity__gte=1).order_by(
                'price')

        paginator = Paginator(products, 3)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)

        content = {
            'links_menu': links_menu,
            'category': category,
            'products': products_paginator,
        }

        return render(request, 'mainapp/products_list.html', content)

    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)

    content = {
        'links_menu': links_menu,
        'hot_product': hot_product,
        'same_products': same_products,
    }

    return render(request, 'mainapp/catalog.html', content)


def contacts(request):
    with open('mainapp/json/contact__locations.json') as f:
        json_data = json.load(f)
    context = {
        'copyright': 'Golubeva Lyubov - GB',
        'title': 'contacts',
        'contact_list': json_data['contacts'],
    }
    return render(request, 'mainapp/contacts.html', context)


def product(request, pk):
    links_menu = ProductCategory.objects.filter(is_active=True, quantity__gte=1)

    product = get_object_or_404(Product, pk=pk)
    same_products = get_same_products(product)

    content = {
        'links_menu': links_menu,
        'product': product,
        'same_products': same_products,
    }
    return render(request, 'mainapp/product.html', content)

mainapp/templates/mainapp/block-footer.html
{% load static %}

<div class="wrapper mobile">
    <div class="container">
        <div class="mobile__content">
            <div>
                <div class="mobile__heading">Mobile app</div>
                <div class="mobile__title">Find. Follow. Favorite.</div>
                <div class="mobile__description">Save your favorites and share your style.</div>
            </div>
            <div class="mobile__buttons">
                <a href="#"><img alt="" src="{% static 'img/app-store.png' %}"/></a>
                <a href="#"><img alt="" src="{% static 'img/google-play.png' %}"/></a>
            </div>
        </div>
    </div>
</div>

<div class="wrapper footer">
    <div class="container">
        <div class="footer__content">
            <div class="footer__nav">
                <div>
                    <h3>Contact us</h3>
                    <address>
                        132A Bridge Road Richmond VIC
                        Australia.
                    </address>
                    <div>
                        Talk to us on <a href="tel:000000">1300 132</a>
                        <a href="mailto:info@interior.com">info@interior.com</a>
                    </div>
                </div>
                <div>
                    <h3>Useful Information</h3>
                    <div>
                        <ul>
                            <li><a href="#">Sales terms</a></li>
                            <li><a href="#">Customer care</a></li>
                            <li><a href="#">Delivery</a></li>
                        </ul>
                        <ul>
                            <li><a href="#">Architect accounts</a></li>
                            <li><a href="#">Careers</a></li>
                            <li><a href="#">Exchanges & returns</a></li>
                        </ul>
                    </div>
                </div>
                <div>
                    <h3>Let’s Stay in Touch!</h3>
                    <p>Suscribe to know about our latest news, products and special offers just for
                        suscribers.</p>
                    <input placeholder="your email address" type="email"/>
                </div>
            </div>
            <div class="footer__copy">
                <div>© Copyright - {{ copyright|upper }} {% now "Y" %}</div>
                <div><img alt="" src="{% static 'img/social-links.png' %}"/></div>
                <div>
                    <a href="#">Terms & Conditions</a> / <a href="#">Privacy policy & Cookies</a>
                </div>
            </div>
        </div>
    </div>
</div>

mainapp/templates/mainapp/block-header.html
<div class="wrapper header{{ className|default:"" }}">
    <div class="container">
        <div class="header__items">
            <div class="header__logo"></div>
            <div class="header__menu">
                {% include 'mainapp/include/inc_main_menu.html' %}
            </div>
        </div>
    </div>
</div>

mainapp/templates/mainapp/block-title.html
{% if title %}
    <div class="wrapper page-title{{ className|default:"" }}">
        <div class="container">
            <div class="title">{{ title|default:""|title }}</div>
        </div>
    </div>
{% endif %}

mainapp/templates/mainapp/catalog.html
{% extends 'mainapp/page-layout.html' %}
{% load static %}
{% load avatar_tag %}

{% block content %}
    {% include 'mainapp/include/block-submenu.html' %}

    <div class="wrapper">
        <div class="container">
            <div class="product">
                <div class="product__cell">
                    <div style="margin: 50px 0px 0px 50px">
                        <img src="{{ hot_product.image|media_folder_products }}">
                    </div>
                    <div class="product__gallery">
                        <span class="product__gallery-item">
                            <img alt="" src="/media/{{ hot_product.image }}"/>
                        </span>
                        <span class="product__gallery-item">
                            <img alt="" src="/media/{{ hot_product.image }}"/>
                        </span>
                        <span class="product__gallery-item product__gallery-item_selected">
                            <img alt="" src="/media/{{ hot_product.image }}"/>
                        </span>
                    </div>
                </div>

                <div class="product__cell">
                    <div class="product__title">{{ hot_product.name }}</div>
                    <div class="product__subtitle">Hot Deal</div>
                    <div class="product__price"><b>{{ hot_product.price }}</b>€</div>
                    <div class="product__button">
                        <a href='{% url 'basket:add' hot_product.pk %}' class="button button_red">
                            <span class="button_text">Order us</span>
                        </a>
                    </div>
                    <div class="product__info">
                        <p>{{ hot_product.description }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="wrapper">
        <div class="container">
            <div class="section-header">
                <span class="section-title">Related products</span>
                <span class="section-aside">Explore all</span>
            </div>
            <div class="tiles">
                {% for product in same_products %}
                    <a class="tiles__tile" href="{% url 'catalog:product' product.pk %}">
                        <div class="tile-info">
                            <div class="tile-info__content">
                                <span class="button button_round"></span>
                                <div class="tile-info__title">{{ product.name }}</div>
                                <div class="tile-info__description">{{ product.short_desc }}</div>
                            </div>
                        </div>
                        <img alt="{{ product.name }}" src="{{ product.image|media_folder_products }}"/>
                    </a>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}

mainapp/templates/mainapp/contacts.html
{% extends 'mainapp/page-layout.html' %}
{% load static %}
{% block content %}
    {% include 'mainapp/block-title.html' with title='Contacts' %}

    <div class="tiles">
        {% for address in contact_list %}
            <div class="tiles__tile tiles__tile_m">
                <div class="contacts-info">
                    <div class="contacts-info__title">{{ address.title }}</div>
                    <dl>
                        <dt>
                            <b>Phone</b>
                        </dt>
                        <dd>
                            <a href="tel:0">{{ address.phone }}</a>
                        </dd>
                        <dt>
                            <b>E-mail</b>
                        </dt>
                        <dd>
                            <a href="mailto:mail">{{ address.email }}</a>
                        </dd>
                        <dt>
                            <b>Address</b>
                        </dt>
                        <dd>
                            <span>{{ address.address }}</span>
                        </dd>
                    </dl>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

mainapp/templates/mainapp/index.html
{% extends 'mainapp/page-layout.html' %}
{% load static %}

{% block header %}
    {% include 'mainapp/block-header.html' with className=" header_absolute" %}
{% endblock %}
{% block content %}
    <div class="wrapper slider slider_top">
        <div class="container">
            <div class="info">
                <div class="info__header color-green">Trending</div>
                <div class="info__title">Fishnet chair</div>
                <div class="info__description">
                    Seat and back with upholstery made of cold cure foam. Steel frame, available in matt
                    powder-coated black or highly polished chrome.
                </div>
                <a class="button" href="{% url 'product' %}">
                    <span class="button_text">Order us</span>
                </a>
            </div>
            <div class="slider-bullets">
                <span class="slider-bullets__bullet"></span>
                <span class="slider-bullets__bullet slider-bullets__bullet_active"></span>
                <span class="slider-bullets__bullet"></span>
            </div>
        </div>
    </div>

 <div class="wrapper section">
        <div class="container">
            <div class="section-header">
                <span class="section-tabs">
                    <span class="section-tabs__tab section-tabs__tab_active">Featured</span>
                    <span class="section-tabs__tab">New</span>
                </span>
                <span class="section-aside">Explore all</span>
            </div>
            <div class="tiles">

                {% for product in products %}
                    <a class="tiles__tile" href="{% url 'catalog:product' product.pk %}">

                        <div class="tile-info">
                            <div class="tile-info__content">
                                <span class="button button_round"></span>
                                <div class="tile-info__title">{{ product.name }}</div>
                                <div class="tile-info__description">{{ product.short_desc }}</div>
                            </div>
                        </div>
                        <img src="media/{{ product.image }}" alt="">
                    </a>
                {% endfor %}

            </div>
        </div>
    </div>


    <div class="wrapper">
        <div class="container">
            <div class="promo">
                <div class="promo-item">
                    <img alt="" src="{% static 'img/promo-img1.png' %}"/>
                    <div class="info info_s">
                        <div class="info__header color-blue">Exclusive</div>
                        <div class="info__title">Fishnet chair</div>
                        <div class="info__description">
                            Seat and back with upholstery made of cold cure foam. Steel frame, available in matt
                        </div>
                        <a class="button" href="{% url 'product' %}">
                            <span class="button_text">Order us</span>
                        </a>
                    </div>
                </div>
                <div class="promo-item">
                    <img alt="" src="{% static 'img/promo-img.png' %}"/>
                    <div class="info info_s">
                        <div class="info__header color-blue">Exclusive</div>
                        <div class="info__title">Fishnet chair</div>
                        <div class="info__description">
                            Seat and back with upholstery made of cold cure foam. Steel frame, available in matt
                        </div>
                        <a class="button" href="{% url 'product' %}">
                            <span class="button_text">Order us</span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% endblock %}

mainapp/templates/mainapp/page-layout.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    {% block title %}
        <title>{{ title|title }}</title>
    {% endblock %}

    {% block css_lib %}
        <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;300;400;
        700&display=swap" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
    {% endblock %}

    {% block css %}
    {% endblock %}

    {% block js_lib %}
    <script type="text/javascript" src="{% static 'js/lib/jquery-3.2.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/lib/bootstrap.min.js' %}"></script>
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>
<body>
<div id="page">
    {% block header %}
        {% include 'mainapp/block-header.html' %}
    {% endblock %}

    {% block content %}
    {% endblock %}

    {% block footer %}
        {% include 'mainapp/block-footer.html' %}
    {% endblock %}
</div>
</body>
</html>


{#    {% block title %}#}
{#        {% if title %}#}
{#            <div class="wrapper" id="page-title">#}
{#                <div class="container">#}
{#                    <div class="title">{{ title|title }}</div>#}
{#                </div>#}
{#            </div>#}
{#        {% endif %}#}
{#    {% endblock %}#}
{##}
{#    <div class="wrapper section">#}
{#        <div class="container">#}
{#            {% block content %}#}
{#            {% endblock %}#}
{#        </div>#}
{#    </div>#}
{##}

mainapp/templates/mainapp/product.html
{% extends 'mainapp/page-layout.html' %}
{% load static %}
{% load avatar_tag %}

{% block content %}
    {% include 'mainapp/include/block-submenu.html' %}
    <div class="product">
        <div class="product__cell">
            <div style="margin: 50px 0px 0px 50px">
                <img alt="" src="/media/{{ product.image }}"/>
            </div>
            <div class="product__gallery">
                        <span class="product__gallery-item">
                            <img alt="" src="/media/{{ product.image }}"/>
                        </span>
                <span class="product__gallery-item">
                            <img alt="" src="/media/{{ product.image }}"/>
                        </span>
                <span class="product__gallery-item product__gallery-item_selected">
                            <img alt="" src="/media/{{ product.image }}"/>
                        </span>
            </div>
        </div>


        <div class="product__cell">
            <div class="product__title">{{ product.name }}</div>
            <div class="product__price"><b>{{ product.price }}</b> euro</div>
            <div class="product__button">
                <a href='{% url 'basket:add' product.pk %}' class="button button_red">
                    <span class="button_text">Order us</span>
                </a>
            </div>
            <div class="product__info">
                <p>{{ product.description }}</p>
            </div>
        </div>
    </div>

    {##}
    {##}
    {#    <div class="wrapper section">#}
    {#        <div class="container">#}
    <div class="section-header">
        <span class="section-title">Related products</span>
        <span class="section-aside">Explore all</span>
    </div>
    <div class="tiles">
        {% for product in same_products %}
            <a class="tiles__tile" href="{% url 'catalog:product' product.pk %}">
                <div class="tile-info">
                    <div class="tile-info__content">
                        <span class="button button_round"></span>
                        <div class="tile-info__title">{{ product.name }}</div>
                        <div class="tile-info__description">{{ product.short_desc }}</div>
                    </div>
                </div>
                <img alt="{{ product.name }}" src="{{ product.image|media_folder_products }}"/>
            </a>
        {% endfor %}
    </div>
    </div>
    {#    </div>#}
    {#    </div>#}
{% endblock %}

mainapp/templates/mainapp/products_list.html
{% extends 'mainapp/page-layout.html' %}
{% load static %}
{% load avatar_tag %}

{% block content %}
    {% include 'mainapp/include/block-submenu.html' %}

    <div class="tiles">
        <div class="paginator">
            {% if products.has_previous %}
                <a href="{% url 'catalog:page' category.pk products.previous_page_number %}"><</a>
            {% endif %}
            <span class="current">
                    Page {{ products.number }} of {{ products.paginator.num_pages }}
                </span>
            {% if products.has_next %}
                <a href="{% url 'catalog:page' category.pk products.next_page_number %}">></a>
            {% endif %}
        </div>
        {% for product in products %}
            <a class="tiles__tile" href="{% url 'catalog:product' product.pk %}">
                <div class="tile-info">
                    <div class="tile-info__content">
                        <span class="button button_round"></span>
                        <div class="tile-info__title">{{ product.name }}</div>
                        <div class="tile-info__description">{{ product.short_desc }}</div>
                    </div>
                </div>
                <img alt="{{ product.name }}" src="{{ product.image|media_folder_products }}"/>
            </a>
        {% endfor %}
    </div>

{% endblock %}