adminapp/urls.py
from django.urls import path
from adminapp.views import users, categories, products

app_name = 'adminapp'
urlpatterns = [
    path('users/read/', users.UserListView.as_view(), name='users'),
    path('users/delete/<int:pk>', users.UserDeleteView.as_view(), name='user_delete'),

    path('categories/create', categories.ProductCategoryCreateView.as_view(), name='category_create'),
    path('categories/read/', categories.ProductCategoryListView.as_view(), name='categories'),
    path('categories/update/<int:pk>', categories.ProductCategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>', categories.ProductCategoryDeleteView.as_view(), name='category_delete'),

    path('products/create/category/<int:pk>', products.product_create, name='product_create'),
    path('products/read/category/<int:pk>', products.products, name='products'),
    path('products/read/<int:pk>', products.ProductDetailView.as_view(), name='product_read'),
    path('products/update/<int:pk>', products.product_update, name='product_update'),
    path('products/delete/<int:pk>', products.ProductDeleteView.as_view(), name='product_delete'),
]

authapp/urls.py
from django.urls import path, re_path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.verify, name='verify'),
]

basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>/', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit'),
]

geekshop/urls.py
import debug_toolbar

import mainapp.views as mainapp
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from geekshop import settings

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('', include('social_django.urls', namespace='social')),
    path('product/', mainapp.product, name='product'),
    path('catalog/', include('mainapp.urls', namespace='catalog')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('contacts/', mainapp.contacts, name='contacts'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('admin/', include('adminapp.urls', namespace='admin')),
    path('order/', include('ordersapp.urls', namespace='order')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

mainapp/urls.py
import mainapp.views as mainapp
from django.urls import path

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.catalog, name='index'),
    path('category/<int:pk>/', mainapp.catalog, name='category'),
    path('category/<int:pk>/<int:page>/', mainapp.catalog, name='page'),
    path('product/<int:pk>/', mainapp.product, name='product'),
]

ordersapp/urls.py
from django.urls import path

import ordersapp.views as ordersapp

app_name = "ordersapp"

urlpatterns = [
    path('', ordersapp.OrderList.as_view(), name='orders_list'),
    path('forming/complete/<int:pk>/', ordersapp.order_forming_complete, name='order_forming_complete'),
    path('create/', ordersapp.OrderItemsCreate.as_view(), name='order_create'),
    path('read/<int:pk>/', ordersapp.OrderRead.as_view(), name='order_read'),
    path('update/<int:pk>/', ordersapp.OrderItemsUpdate.as_view(), name='order_update'),
    path('delete/<int:pk>/', ordersapp.OrderDelete.as_view(), name='order_delete'),
    path('product/<int:pk>/price/', ordersapp.get_product_price)
]

mainapp/models.py
from django.db import models

class ProductCategory(models.Model):
    name = models.CharField(verbose_name='Name', max_length=64, unique=True)
    description = models.TextField(verbose_name='Description', blank=True)
    is_active = models.BooleanField(db_index=True, default=True, verbose_name='Active')

    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='Name', max_length=128)
    image = models.ImageField(upload_to='product_images', blank=True)
    short_desc = models.CharField(verbose_name='Short description', max_length=60, blank=True)
    description = models.TextField(verbose_name='Description', blank=True)
    price = models.DecimalField(verbose_name='Price', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveSmallIntegerField(verbose_name='In stock', default=0)
    is_active = models.BooleanField(db_index=True, default=True, verbose_name='Active')

    def __str__(self):
        return f'{self.name} ({self.category.name})'

    @staticmethod
    def get_items():
        return Product.objects.filter(is_active=True).order_by('category', 'name')

mainapp/views.py
import json
import os
import random

from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import get_object_or_404, render

from .models import Product, ProductCategory

JSON_PATH = 'mainapp/json'


def load_from_json(file_name):
    with open(os.path.join(JSON_PATH, file_name + '.json'), 'r') as infile:
        return json.load(infile)


def get_hot_product():
    products = Product.objects.filter(is_active=True, category__is_active=True, quantity__gte=1)
    return random.sample(list(products), 1)[0]


def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category, quantity__gte=1).exclude(pk=hot_product.pk)[
                    :3]

    return same_products


def main(request):
    products = Product.objects.filter(category__is_active=True, quantity__gte=1)[:3]
    context = {
        'copyright': 'Golubeva Lyubov - GB',
        'products': products,
        # 'new_products': Product.objects.all()[3:7],
    }
    # print(products.query)
    return render(request, 'mainapp/index.html', context)


def catalog(request, pk=None, page=1):
    links_menu = ProductCategory.objects.filter(is_active=True)

    if pk:
        if pk == '0':
            category = {
                'pk': 0,
                'name': 'all'
            }
            products = Product.objects.filter(is_active=True, category__is_active=True, quantity__gte=1).order_by(
                'price')
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True,
                                              quantity__gte=1).order_by(
                'price')

        paginator = Paginator(products, 3)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)

        content = {
            'links_menu': links_menu,
            'category': category,
            'products': products_paginator,
        }

        return render(request, 'mainapp/products_list.html', content)

    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)

    content = {
        'links_menu': links_menu,
        'hot_product': hot_product,
        'same_products': same_products,
    }

    return render(request, 'mainapp/catalog.html', content)


def contacts(request):
    with open('mainapp/json/contact__locations.json') as f:
        json_data = json.load(f)
    context = {
        'copyright': 'Golubeva Lyubov - GB',
        'title': 'contacts',
        'contact_list': json_data['contacts'],
    }
    return render(request, 'mainapp/contacts.html', context)


def product(request, pk):
    links_menu = ProductCategory.objects.filter(is_active=True, quantity__gte=1)

    product = get_object_or_404(Product, pk=pk)
    same_products = get_same_products(product)

    content = {
        'links_menu': links_menu,
        'product': product,
        'same_products': same_products,
    }
    return render(request, 'mainapp/product.html', content)

mainapp/templates/mainapp/include/block-submenu.html
<div class="wrapper{{ className|default:"" }}">
    <div class="container">
        <div class="section-header">
            <span class="section-tabs section-tabs_small">
                {% for link_item in links_menu %}
                    <a
                            {% if category.pk == link_item.pk %}
                                class="section-tabs__tab section-tabs__tab_active"
                            {% else %}
                                class="section-tabs__tab"
                            {% endif %}
                                href="{% url 'catalog:category' link_item.pk %}"
                                title="{{ link_item.name }}"
                    >{{ link_item.name }}</a>
                {% endfor %}
            </span>
            <span class="section-aside">
              <a href="{% url 'catalog:category' 0 %}">Explore all</a>
            </span>
        </div>
    </div>
</div>

mainapp/templates/mainapp/include/inc_main_menu.html
{% load static %}
<a
    href="{% url 'main' %}"
{% if request.resolver_match.url_name == 'main' %}
    class="header__link header__link_active"
{% else %}
    class="header__link"
{% endif %}>Home</a>

<a
    href="{% url 'catalog:index' %}"
{% if 'catalog' in request.resolver_match.route %}
    class="header__link header__link_active"
{% else %}
    class="header__link"
{% endif %}>Products</a>

<a
    href="{% url 'contacts' %}"
{% if request.resolver_match.url_name == 'contacts' %}
    class="header__link header__link_active"
{% else %}
    class="header__link"
{% endif %}>Contact</a>

    {% if user.is_authenticated %}
        <span class="dropdown">
            <a class="dropdown-toggle header__link" href="" data-toggle="dropdown">
                {{ user.first_name|default:'Unknown user' }}
                <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
                {% if user.is_superuser %}
                <li>
                    <a href="{% url 'admin:users' %}">Admin tools</a>
                </li>
                {% endif %}
                <li>
                    <a href="{% url 'auth:edit' %}">Profile</a>
                </li>
                <li>
                    <a href="{% url 'ordersapp:orders_list' %}">Orders</a>
                </li>
                <li>
                    <a href="{% url 'auth:logout' %}">Logout</a>
                </li>
            </ul>
        </span>
    {% else %}
        <a href="{% url 'auth:login' %}" class="header__link">Login</a>
    {% endif %}


    <a href="{% url 'basket:view' %}" class="header__link">
        Cart items
        <span>
            {% if basket %}
                {{ basket.0.total_cost|floatformat:0 }} euro ({{ basket.0.total_quantity }} pcs)
            {% endif %}
        </span>
    </a>

mainapp/templates/mainapp/include/inc_product.html
{#{% load avatar_tag %}#}
{##}
{#<div class="product">#}
{#    <div class="product__cell">#}
{#        <div style="margin: 50px 0px 0px 50px">#}
{#            <img style="height: 100px" src="{{ hot_product.avatar|media_folder_users }}">#}
{#        </div>#}
{#        <div class="product__gallery">#}
{#                        <span class="product__gallery-item">#}
{#                            <img alt="" src="/media/{{ hot_product.image }}"/>#}
{#                        </span>#}
{#            <span class="product__gallery-item">#}
{#                            <img alt="" src="/media/{{ hot_product.image }}"/>#}
{#                        </span>#}
{#            <span class="product__gallery-item product__gallery-item_selected">#}
{#                            <img alt="" src="/media/{{ hot_product.image }}"/>#}
{#                        </span>#}
{#        </div>#}
{#    </div>#}
{##}
{##}
{#    <div class="product__cell">#}
{#        <div class="product__title">{{ hot_product.name }}</div>#}
{#        <div class="product__subtitle">Hot Deal</div>#}
{#        <div class="product__price"><b>{{ hot_product.price }}</b>€</div>#}
{#        <div class="product__button">#}
{#            <a href='{% url 'basket:add' hot_product.pk %}' class="button button_red">#}
{#                <span class="button_text">Order us</span>#}
{#            </a>#}
{#        </div>#}
{#        <div class="product__info">#}
{#            <p>{{ hot_product.description }}</p>#}
{#        </div>#}
{#    </div>#}
{#</div>#}